# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 325b2860aa37997165a3d07c6b4f800d5a7b4b0ebf7e8dfe7c0977fc4afeea48c969c942e90a7b85594cfe84a4573e2b4317f776e5324f64a01f98596d5ca394

test:
  secret_key_base: d56dc84f12b278fe792aef2e88fc15d40bcaf148fb158f4d1184e53e4fb61644720bb8920ff98a09edcb0ae525c10638daf7c713110618623b7fb1a7469d377d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
